
//----------------------------------------------------
// The following code was generated by jh-javacup-1.3 20240325
// Wed Jun 25 10:52:53 CEST 2025
//----------------------------------------------------

package fr.uha.montivincent.jcupnflex.sample.calculator.reader;

/** CUP generated enum containing nonterminal constants. */
public enum ENonterminal {
  /* nonterminals */
  command,
  instr,
  list,
  expr,
  $START,
  $parenthesis1,
  $parenthesis1$0_many,
   ;
}

