
//----------------------------------------------------
// The following code was generated by jh-javacup-1.3 20240325
// Tue Mar 11 10:34:41 CET 2025
//----------------------------------------------------

package fr.uha.hassenforder.javacup.sample.calculator.reader;

/** CUP generated enum containing nonterminal constants. */
public enum ENonterminal {
  /* nonterminals */
  commands,
  list,
  instr,
  expr,
  $START,
  $parenthesis1,
  $parenthesis1$0_many,
   ;
}

