
//----------------------------------------------------
// The following code was generated by jh-javacup-1.3 20240325
// Tue Mar 11 10:34:41 CET 2025
//----------------------------------------------------

package fr.uha.hassenforder.javacup.sample.calculator.reader;

/** CUP generated enum containing terminal constants. */
public enum ETerminal {
  /* terminals */
   error,
   EOF,
   OOA,
   EQUAL,
   PLUS,
   MINUS,
   TIMES,
   DIVIDE,
   LPAREN,
   RPAREN,
   EOLN,
   NUMBER,
   ID,
   UPLUS,
   UMINUS,
   ;
}

